### ISSUE TITLE
NeighborNet

### ISSUE THREAD

**Issue by rvwfels** [KlausVigo/phangorn#1]
Hi, 
this is a great package, many thanks for developing it. I am using SplitsTree for the visualization of NeighborNets, and I was wondering whether there are any plans to improve the visualization of these networks in phangorn? Right now, the networks I am generating with my data are not quite satisfactory. Or maybe it would make sense to plot them using a different function, not plot.networx? Thanks and best, 
Ruprecht von Waldenfels

**Comment by KlausVigo** [comment]
Hi Ruprecht, 
What improvements do you want to see in plot.networx? What will it take to satisfy your needs? There is also a difference whether you plot on the normal graphics device in "2D" or use the "3"D rgl device.
Klaus

**Comment by rvwfels** [comment]
Basically, the fonts were not very clear and the lines, I guess, too thin. I will experiment around a bit and then tell you in more details. 
Best, 
Ruprecht

**Comment by KlausVigo** [comment]
You can change the thickness of the lines with edge.width parameter, the font size with cex or switch between bold, italic with font. 
Best, 
Klaus

**Comment by rvwfels** [comment]
Hi Klaus,

I am now returning to phangorn, and for my data, the graphs are not 
satisfactory because they give crossing lines where Splitstree avoids 
them. I'm enclosing two pictures from phangorn and splitstree, so you 
can see, what I mean, as well as the distance data I use to get these 
graphs:




Thanks and best!
Ruprecht

**Comment by rvwfels** [comment]
I forgot the data, here it is:
14
ru 0 0.569682862961885 0.591440798858773 0.431776275353411 
0.64694551458448 0.673894912427023 0.694814814814815 0.681784201345627 
0.633149171270718 0.553032480597873 0.616197183098592 0.588576158940397 
0.606020942408377 0.613409029467424
by 0.569682862961885 0 0.666188700889016 0.611415393485154 
0.685495316491626 0.703671581381902 0.707008016550297 0.683504340962904 
0.679694137638063 0.658757062146893 0.692599620493359 0.683478735005453 
0.693205394190871 0.689309878213803
uk 0.591440798858773 0.666188700889016 0 0.531268973891925 
0.693625386127492 0.714326484018265 0.730467762326169 0.715819064656274 
0.696632340662399 0.672696910659616 0.705505077498664 0.680989937449007 
0.711156393275599 0.698421193470698
uka 0.431776275353411 0.611415393485154 0.531268973891925 0 
0.682526661197703 0.679015837104072 0.726178781925344 0.693759436336185 
0.651932165693634 0.616872197309417 0.64704293815825 0.634730538922156 
0.652050554552489 0.656875834445928
pl 0.64694551458448 0.685495316491626 0.693625386127492 
0.682526661197703 0 0.582490518331226 0.723583460949464 
0.687729417933928 0.667714285714286 0.644691780821918 0.658136300417246 
0.64592094196804 0.67612293144208 0.667033571821684
pla 0.673894912427023 0.703671581381902 0.714326484018265 
0.679015837104072 0.582490518331226 0 0.72431011826544 0.701763762693747 
0.679918152586963 0.669172932330827 0.678813559322034 0.67374681393373 
0.706923890063425 0.692007797270955
cz 0.694814814814815 0.707008016550297 0.730467762326169 
0.726178781925344 0.723583460949464 0.72431011826544 0 0.570744680851064 
0.69196776709124 0.699364675984752 0.696208887773035 0.707359522625559 
0.695998071359691 0.715377033021193
sk 0.681784201345627 0.683504340962904 0.715819064656274 
0.693759436336185 0.687729417933928 0.701763762693747 0.570744680851064 
0 0.649865951742627 0.655290102389078 0.669482846902202 
0.665555270582201 0.683288737533447 0.68523185483871
sl 0.633149171270718 0.679694137638063 0.696632340662399 
0.651932165693634 0.667714285714286 0.679918152586963 0.69196776709124 
0.649865951742627 0 0.591632292280495 0.60728628800918 0.601955708944492 
0.653478491768455 0.65813377374071
hr 0.553032480597873 0.658757062146893 0.672696910659616 
0.616872197309417 0.644691780821918 0.669172932330827 0.699364675984752 
0.655290102389078 0.591632292280495 0 0.520658682634731 
0.482515337423313 0.571468144044321 0.605677346824058
sr 0.616197183098592 0.692599620493359 0.705505077498664 
0.64704293815825 0.658136300417246 0.678813559322034 0.696208887773035 
0.669482846902202 0.60728628800918 0.520658682634731 0 0.510234351824384 
0.571662571662572 0.609223971278652
sra 0.588576158940397 0.683478735005453 0.680989937449007 
0.634730538922156 0.64592094196804 0.67374681393373 0.707359522625559 
0.665555270582201 0.601955708944492 0.482515337423313 0.510234351824384 
0 0.575856443719413 0.603710883411797
mk 0.606020942408377 0.693205394190871 0.711156393275599 
0.652050554552489 0.67612293144208 0.706923890063425 0.695998071359691 
0.683288737533447 0.653478491768455 0.571468144044321 0.571662571662572 
0.575856443719413 0 0.60763520678685
bg 0.613409029467424 0.689309878213803 0.698421193470698 
0.656875834445928 0.667033571821684 0.692007797270955 0.715377033021193 
0.68523185483871 0.65813377374071 0.605677346824058 0.609223971278652 
0.603710883411797 0.60763520678685 0




Am 08.09.2015 um 11:46 schrieb Ruprecht von Waldenfels:
> Hi Klaus,
>
> I am now returning to phangorn, and for my data, the graphs are not 
> satisfactory because they give crossing lines where Splitstree avoids 
> them. I'm enclosing two pictures from phangorn and splitstree, so you 
> can see, what I mean, as well as the distance data I use to get these 
> graphs:
>
>
>
>
> Thanks and best!
> Ruprecht

**Comment by KlausVigo** [comment]
Dear Ruprecht, 
I changed a few things in phangorn on the github version. There are now to function read.nexus.networx / write.nexus.networx to exchange networks with SplitsTree. 
The function to plot networks now often uses less edges, seems pretty much the same as SplitsTree. The number of splits differs slightly for neighborNet, but as SplitsTree is not open source I have no way to easily trace these differences back. Mostly the networks are the same and the plotting. And the overall appearance is also improved. 
Regards, 
Klaus

**Comment by rvwfels** [comment]
Dear Klaus,
that sounds great! I will not have a chance to look at it before in two 
weeks, but I am looking forward to doing so!
Best,
Ruprecht
Am 19.08.2016 um 12:40 schrieb Klaus Schliep:

**Comment by rvwfels** [comment]
Dear Klaus,
many thanks again!
  I now wonder - is there a way to color the labels individually, or do 
they all necessarily have the same color?

Thank you, sorry if this is a silly question,
Ruprecht


Am 19.08.2016 um 12:40 schrieb Klaus Schliep:

**Comment by KlausVigo** [comment]
Dear @rvwfels 

plot.networx() allows to labels, edges or splits etc. to have different colors.  E.g.  
example(neighborNet)
plot(nnet, "2D", tip.color=1:8)
plot.networx() has actually quite a lot of options (for help see ?plot.networx): 
args(plot.networx)
function (x, type = "3D", use.edge.length = TRUE, show.tip.label = TRUE, 
    show.edge.label = FALSE, edge.label = NULL, show.node.label = FALSE, 
    node.label = NULL, show.nodes = FALSE, tip.color = "black", 
    edge.color = "black", edge.width = 3, edge.lty = 1, split.color = NULL, 
    split.width = NULL, split.lty = NULL, font = 3, cex = par("cex"), 
    cex.node.label = cex, cex.edge.label = cex, col.node.label = tip.color, 
    col.edge.label = tip.color, font.node.label = font, font.edge.label = font, 
    ...) 
Drop me an email if you get lost. 

Cheers, 
Klaus
