### ISSUE TITLE
Confidence support for SuperNetwork

### ISSUE THREAD

**Issue by alexweisberg** [KlausVigo/phangorn#10]
I have a SuperNetwork that was created by SplitsTree from several hundred individual gene clusters, however not all gene clusters contain all taxa. I would like to color edges based on how many of the phylogenies contain that split. When I try to use the addConfidences function, I get the error:

`library(phangorn)`
`splitstreenet <- read.nexus.networx("./splitstree_supernetwork.nex")`
`alltrees<-read.tree("./alltrees.tre")`
`y<-addConfidences(splitstreenet,alltrees)`
`edge.col<- createLabel(y, splitstreenet, label="black", "edge", nomatch="grey")`
`plot.networx(splitstreenet, "2D")`

`Error in FUN(X[[i]], ...) : one tree has a different number of tips
Calls: addConfidences ... as.splits.multiPhylo -> prop.part -> .compressTipLabel -> lapply -> FUN`

I get a similar error if I try to use as.splits(alltrees) instead in the same function. 

Is there any way this type of tree can be supported?

**Comment by KlausVigo** [comment]
Should work now
