### ISSUE TITLE
Long vectors not supported when doing computation with dist.hamming

### ISSUE THREAD

**Issue by aeonsofmusic** [KlausVigo/phangorn#100]
Hi Klaus,

I have a dataset of about 130000 sequences, and it seems to be too much for R to handle when I use dist.hamming. I'd like to be able to compute every pairwise distance in the dataset, so subsetting at the FASTA level doesn't seem to be an option. Is there some way to store the subsets of the distance matrix partway so this error doesn't occur?

I am relatively new to R, so any suggestions will be appreciated! 

Thank you!

**Comment by KlausVigo** [comment]
Dear @aeonsofmusic, 
to handle long vectors quite a some code has to be rewritten, so this unfortunately won't happen too soon.
Also 130000 sequences are a lot so the analysis would take forever.
Have you tried using unique() on the dataset to remove duplicated sequences. 
Maybe this reduces your dataset enough, and you don't loose information. 
Regards, 
Klaus
