### ISSUE TITLE
Should the RF.dist function emit a warning for non-binary tree if Normalize=FALSE?

### ISSUE THREAD

**Issue by hyanwong** [KlausVigo/phangorn#103]
At the moment the RF.dist function emits a warning if used on non-binary trees. By my understanding, non-binary trees are only problematic in this circumstance because of difficulties in specifying the appropriate normalisation constant. Might it be useful, therefore, to only emit the warning if `Normalize=TRUE`?

**Comment by KlausVigo** [comment]
Hi @hyanwong,
 
thanks for the suggestion. It would be possible to emit this warning only when `normalize=FALSE`. In phangorn, I normalize it with the sum of the number of internal edges for each of the trees, so it is adjusted for when using `normalize=TRUE`. 
```
> library(phangorn)
> tree1 <- rtree(13, rooted=FALSE)
> tree2 <- rtree(13, rooted=FALSE)
> tree3 <- stree(13)
> 
> RF.dist(tree1, tree2)
[1] 20
> RF.dist(tree1, tree3)
Trees are not binary!
[1] 10
> RF.dist(tree1, tree2, normalize = TRUE)
[1] 1
> RF.dist(tree1, tree3, normalize = TRUE)
Trees are not binary!
[1] 1
```
So here both 10 and 20 are the maximum possible distances between the set of trees. However I think most users are not aware of that this "feature" of the Robinson-Foulds distance. 

Cheers, 
Klaus

**Comment by hyanwong** [comment]
Thanks for the reply. I do think that the RF distance is well defined when unnormalised, so it seems a bit odd to emit a warning when normalize=FALSE, as the metric is perfectly valid (it made me worry that the RF metric was inappropriate for trees with polytomies). But whatever you think is most helpful for users.
