### ISSUE TITLE
Unit for simSeq function

### ISSUE THREAD

**Issue by richelbilderbeek** [KlausVigo/phangorn#11]
Using the simSeq function is easy:

```
phangorn::simSeq(
    x = ape::rcoal(4), # A random phylogeny
    l = 10, # sequence_length in base pairs
    rate = 0.5 # mutation_rate in unknown unit
  )
```

What I miss from the documentation, is the unit of `rate`. I expect this is the per-locus chance of mutation per one unit time. Is this correct?

I do volunteer to create a Pull Request changing the current documentation of the function arguments from:

```
rate	rate.
```

to 
```
rate	per-locus chance of mutation per one unit of time.
```

**Comment by KlausVigo** [comment]
@richelbilderbeek That sounds about right, even chance sounds a bit like probability, which it is not. 
Maybe it seen  can also seen as a scaler for the edge weights like the -s option in seq-gen as both are multiplied. If one wants to simulate a discrete rate model as given in the example the rates should be centred around 1. I added it as I submit a new version to CRAN.

**Comment by richelbilderbeek** [comment]
Hi Klaus,

Thanks for your efforts! I see in your newest commit your current wording:

```
mutation rate or scaler for the edge length, a numerical value greater than zero.
```

Still, my question is unanswered. What is the unit of a `rate` of `1.0`? And what does such a rate mean? 

Thanks for taking the time to help your users!

**Comment by KlausVigo** [comment]
You always have the product of edge length and the rate, so the rate alone means nothing. Usually you give the edge length in expected number of substitutions per site (in this case the rate or mean of rates is one). However if you have edge length in number of years you would need to adopt the rate.
