### ISSUE TITLE
pratchet error with minimal example

### ISSUE THREAD

**Issue by kbhoehn** [KlausVigo/phangorn#110]
Hello. I've recently updated my version of phangorn but noticed the pratchet function fails with the small example below. This example works with version 2.5.5 but gives "Error in x[[i]] : subscript out of bounds" in the latest version:

data <- phangorn::phyDat(ape::as.DNAbin((rbind(
  "seq1"=c("C","C"),
  "seq2"=c("C","A"),
  "seq3"=c("A","C")
  ))))
phangorn::pratchet(data)

**Comment by KlausVigo** [comment]
Hi @kbhoehn, 
Thanks for spotting the bug. Fixed on github now. I will submit a new version to CRAN today!
Regards, Klaus
