### ISSUE TITLE
Phangorn removal warning from CRAN

### ISSUE THREAD

**Issue by danlwarren** [KlausVigo/phangorn#111]
Hi Klaus!  I just got an email from CRAN saying phangorn was going to be pulled in a couple of weeks if some issues weren't fixed (https://cran.r-project.org/web/checks/check_results_phangorn.html), and that RWTY will be pulled due to dependencies as well.  Just wanted to check in with you and see if you are working on these, because we'll need to find a workaround if not.  

Cheers!

**Comment by dwbapst** [comment]
If we look at the R CHECK output resulting from CRAN's automated checking, we see that the WARNING errors appear to occur with trying to build vignettes:

https://cran.r-project.org/web/checks/check_results_phangorn.html

https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/phangorn-00check.html

```
checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
  ...
--- re-building 'AdvancedFeatures.Rmd' using rmarkdown
--- finished re-building 'AdvancedFeatures.Rmd'

--- re-building 'Ancestral.Rmd' using rmarkdown
Quitting from lines 57-59 (Ancestral.Rmd)
Error: processing vignette 'Ancestral.Rmd' failed with diagnostics:
there is no package called 'seqLogo'
--- failed re-building 'Ancestral.Rmd'

--- re-building 'IntertwiningTreesAndNetworks.Rmd' using rmarkdown
--- finished re-building 'IntertwiningTreesAndNetworks.Rmd'

--- re-building 'Networx.Rmd' using rmarkdown
--- finished re-building 'Networx.Rmd'

--- re-building 'Trees.Rmd' using rmarkdown
--- finished re-building 'Trees.Rmd'

SUMMARY: processing the following file failed:
  'Ancestral.Rmd'

Error: Vignette re-building failed.
Execution halted
```

It looks like the real problem is not being able to find `seqLogo` package in the `Ancestral.Rmd` vignette. So presumably removing the reference to that package in that vignette should allow `phangorn` to safely pass CRAN testing.

**Comment by bomeara** [comment]
[seqLogo is in bioconductor](https://bioconductor.org/packages/release/bioc/html/seqLogo.html) -- has been for 14 years, [last updated 5 months ago](https://github.com/ivanek/seqLogo), and is still available at BioConductor. I don't see anything in the [Writing R Extensions guide](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) about using BioConductor packages in vignettes, but maybe this is now a problem.

**Comment by KlausVigo** [comment]
Hi all, 

a new version is on the way to CRAN. It probably needs a day for the reverse dependency checks on their side, if everything works fine. On the other hand last time it was for 3 month in the loop. 
@bomeara, it used to be that vignettes could call suggested packages, that seems not the case any more or is enforced nowadays. Now I am not sure what suggested would be any good for.

I was pretty busy the last weeks moving flats and teaching so did not take Ripley's message serious enough. On the other hand it's ridiculous to set the dead line for on a holiday. As it was yesterday public holiday in Austria, where CRAN lives, so much for work-life balance in academia.  

Regards, 
Klaus

**Comment by dwbapst** [comment]
Even disregarding that CRAN 'lives' in Austria (a concept that suggests
that CRAN itself is an organism, in which case I do not want to know
anything more about its biology, or appearance, or phylum), you'd think
they'd give more time for a response during an ongoing global pandemic!

**Comment by dwbapst** [comment]
It looks like v2.6.3 is now on CRAN and so our nightmare can be over

https://cran.r-project.org/web/packages/phangorn/
