### ISSUE TITLE
getRoot error?

### ISSUE THREAD

**Issue by BEAST-Community** [KlausVigo/phangorn#115]
> tr <- read.newick('1155.newick.tre', node.label='label')
> class(tr)
[1] "phylo"
> getRoot(tr@phylo)
Error in getRoot(tr@phylo) : 
  trying to get slot "phylo" from an object (class "phylo") that is not an S4 object

**Comment by KlausVigo** [comment]
Try ```getRoot(tr)```
Regards, 
Klaus
