### ISSUE TITLE
open AA data in phyDat() from read.aa()

### ISSUE THREAD

**Issue by lguy** [KlausVigo/phangorn#119]
Hi there,
Thanks for proving phangorn to the community, it's a highly appreciated tool.
I'm trying to load an amino-acid alignment with read.aa and create a phyDat object with the resulting alignment. I get an error along the way, presumably due to data type conversion. I provide a reproducible example and a possible way to fix it.
```
## Testing phyData.default with AA data read from read.aa
# Reproducing the error: 
states <- c("A", "R", "N", "D", "C", "Q", "E", "G", "H", "I", "L", "K", "M", 
            "F", "P", "S", "T", "W", "Y", "V", "-")
fastaStr <- ">A\nPQR\n>B\nPQS\n>C\nRQS"
fastaFile <- tempfile()
writeLines(fastaStr, fastaFile)
readLines(fastaFile)
alnMat <- read.aa(fastaFile, format="fasta")
aln <- phyDat(alnMat, type ="AA")
aln <- phyDat(alnMat, type ="USER", levels=states)
```
This results in:
```
Error in if (ncol(data) == 1) compress <- FALSE : 
  argument is of length zero
```
I believe this comes from data type conversion in `phyDat.default`, which reads (l. 103):
```
if (inherits(data, "DNAbin") | inherits(data, "AAbin") |  inherits(data, "phyDat")) 
 data <- as.character(data)
```
omitting to first convert to matrix if the data is a list. In comparison, the phyDat.AA reads (l. 171-174):
```
if (inherits(data,"AAbin")){
  if(is.list(data)) data <- as.matrix(data)
  data <- as.character(data)  
}
```
This error is fixed by adding the conditional conversion to matrix in phyDat.default: 
```
  if (inherits(data, "DNAbin") | inherits(data, "AAbin") |
      inherits(data, "phyDat")) {
    if(is.list(data)) data <- as.matrix(data)
    data <- as.character(data)
  }
```

Incidentally, `phyDat` forces the use of `DNA` type if the object is `DNAbin`, but not to `AA` if the object is `AAbin`. I would suggest not coercing the use of `DNA`, because it prevents the user to use their own levels:

```
# Reproducing the error with DNA
states <- c("A", "C", "G", "T", "-")
fastaStr <- ">A\nACG\n>B\nACT\n>C\nACC"
fastaFile <- tempfile()
writeLines(fastaStr, fastaFile)
readLines(fastaFile)
alnMat <- read.dna(fastaFile, format="fasta")
aln <- phyDat(alnMat, type ="DNA")
## This generates an error because phyDat forces type "DNA" is the object is
# DNAbin
aln <- phyDat(alnMat, type ="USER", levels=states)
```
which results in the character `-` disappearing: 
```
>aln
3 sequences with 3 character and 3 different site patterns.
The states are a c g t 
```
Kind regards,
Lionel

**Comment by KlausVigo** [comment]
Hi @lguy, 
thanks for the nice report and suggestions. It is included in this 11bd699. 
It might be best to use `read.phyDat` instead of `read.aa` than less transformations are necessary. 
In your last block `states <- c("a", "c", "g", "t", "-")` needs to be lower case to work. 
Kind regards, 
Klaus

**Comment by lguy** [comment]
Thanks Klaus!
I missed the read.phyDat function. Maybe worth adding it the "See also" section of `read.aa`?

**Comment by KlausVigo** [comment]
Hi Lionel @lguy, 
I will link to `read.phyDat` and might actually stop exporting `read.aa` if no dependency does use it. It is really just a helper function for `read.phyDat`.    
Have a nice weekend, 
Klaus
