### ISSUE TITLE
modelTest for tree with >100 tips

### ISSUE THREAD

**Issue by dferran1** [KlausVigo/phangorn#122]
Hello,
First off, phangorn is tremendously useful for exploring multiple sequence alignments in a streamlined way.

I am getting an error when I attempt to run modelTest on an alignment and tree file with many tips: 
Error in dm[labels, labels] : subscript out of bounds

The exact same code works on an alignment and tree with fewer than 100 tips.  Is there any way to work around this?

Thank you,

David Ferranti

**Comment by KlausVigo** [comment]
Dear David @dferran1, 
is it possible to show me the code you used and send or share the data / tree? So I can figure out what's going wrong. 
Cheers, 
Klaus

**Comment by dferran1** [comment]
[SWS2.introns.removed.incomplete.removed.NT_MACSE.fa.treefile.txt](https://github.com/KlausVigo/phangorn/files/7268838/SWS2.introns.removed.incomplete.removed.NT_MACSE.fa.treefile.txt)
[SWS1.introns.removed.incomplete.removed.NT_MACSE.fa.treefile.txt](https://github.com/KlausVigo/phangorn/files/7268839/SWS1.introns.removed.incomplete.removed.NT_MACSE.fa.treefile.txt
[SWS1.introns.removed.incomplete.removed.NT_MACSE.fa.txt](https://github.com/KlausVigo/phangorn/files/7268841/SWS1.introns.removed.incomplete.removed.NT_MACSE.fa.txt)
[SWS2.introns.removed.incomplete.removed.NT_MACSE.fa.txt](https://github.com/KlausVigo/phangorn/files/7268842/SWS2.introns.removed.incomplete.removed.NT_MACSE.fa.txt)
)


Hi Klaus,

Here are the alignments and trees.  SWS1 has fewer sequences in the alignment and works with modelTest, SWS2 has more sequences and does not work.

Here is the code:

`for (gene in c("SWS1", "SWS2"))
{
    alignment_file <- read.phyDat(paste(gene,".introns.removed.incomplete.removed.NT_MACSE.fa.txt", sep=""), format = "fasta")
    
    phylo_tree <- read.tree(paste(gene, ".introns.removed.incomplete.removed.NT_MACSE.fa.treefile.txt",sep=""))

  
  model_data_frame <- modelTest(alignment_file, phylo_tree, model=c("all"))
  
  write.table(model_data_frame, paste(gene, "ModelFinder.table.txt", sep=""), row.names = FALSE, col.names = TRUE, quote = FALSE, sep="\t")
}
`

**Comment by KlausVigo** [comment]
Dear @dferran1, 
it was a problem with the labels. In the alignment one label is "Danio rerio|SWS2" and in the tree it is just "Danio". 
I made the error message a bit more useful. 
Regards, 
Klaus
