### ISSUE TITLE
treedist() no longer working for non-binary trees

### ISSUE THREAD

**Issue by jc17659** [KlausVigo/phangorn#128]
I have recently returned to some code that previously ran fine using the treedist() function on a large list of unrooted consensus trees against a benchmark topology. It now, however, does not run. 
When I pull out a lone tree to compare to the benchmark and try to use the function I get the error message:

`Error in !is.binary(tree1) | !is.binary(tree2) : non-conformable arrays`

has something changed in using non-binary trees for the function? How could I get around this?

**Comment by KlausVigo** [comment]
Hi @jc17659, 
there weren't any recent changes in `treedist()`. The error message looks strange. Maybe something got wrong with the construction of the consensus tree? Can you send me the trees? 
Regards, 
Klaus

**Comment by jc17659** [comment]
they are just newick plots of some mammals using taxa names produced in tnt, I attempted to attach an example but it does not accept .nex files so changes it to a.txt file

[consensus_1_100.txt](https://github.com/KlausVigo/phangorn/files/9073197/consensus_1_100.txt)
:

**Comment by KlausVigo** [comment]
That's good! I close the issue. Feel free to reopen it, if there are more problems.
