### ISSUE TITLE
install_github() not working

### ISSUE THREAD

**Issue by JoseCAMX** [KlausVigo/phangorn#13]
PC specs: OS - Ubuntu 14.04 64bit; CPU - AMD Fx6300; R - v3.3.2; and RStudio - v1.0.44.

Versión 2.0.4 already installed, getting this message while installing latest github version:

Error : package ‘ape’ 3.5 was found, but >= 4.0 is required by ‘phangorn’

There's no ape 4.0 as far as I know, where do I get it?

**Comment by KlausVigo** [comment]
@JoseCAMX this more or less identical with the latest development / testing version and installation guide is here: http://ape-package.ird.fr/ape_installation.html. You may have to rename the version to 4.0. Emmanuel has just submitted ape 4.0 to CRAN, fingers crossed it is up tomorrow (it is already in ftp://cran.r-project.org/incoming/, but you can't get it from there). If ape is accepted I will push phangorn also to CRAN.
