### ISSUE TITLE
error in networx

### ISSUE THREAD

**Issue by basic99** [KlausVigo/phangorn#130]
version 2.9.0 gives the wrong results for read.nexus.networx("splitstree.nxs")

The input file has 
BEGIN Network;
DIMENSIONS ntax=86 nvertices=805 nedges=1475;

version 2.8.1 gives the correct numbers

[splitstree.nxs.txt](https://github.com/KlausVigo/phangorn/files/9337899/splitstree.nxs.txt)
.

**Comment by KlausVigo** [comment]
Dear @basic99, 
phangorn assumes that edges leading to a label (trivial splits) always exist. In your dataset SplitsTree assign to some internal nodes several labels. Currently phangorn adds edges leading to the labels (with length 0) if these edges do not exist. The number edges and vertices is increased, but the number of taxa stays constant. The plot should look the same as the additional edges have zero edge weight.
Regards, 
Klaus

**Comment by basic99** [comment]
Yes. However, when I examine this object it seems to show different lengths for edges and lengths.

![object_view](https://user-images.githubusercontent.com/2780052/184949338-33229df8-4521-4425-a98d-8f70a85f7d8a.png)

**Comment by KlausVigo** [comment]
Hi @basic99,
I also saw this yesterday and the commit 4b0a7a3f21b3239e291ac926137ad80710408584 should fix this. 
Thanks for the bug reports. 
Regards, 
Klaus
