### ISSUE TITLE
joint method for ancestral sequence inference

### ISSUE THREAD

**Issue by GuangchuangYu** [KlausVigo/phangorn#14]
<https://github.com/KlausVigo/phangorn/blob/master/R/ancestral_pml.R#L62-L63>

```
    type <- match.arg(type)
    pt <- match.arg(type, c("marginal", "joint", "ml", "bayes"))
```

`match.arg` were called twice and the first one counts which doesn't allow 'joint'.

**Comment by GuangchuangYu** [comment]
I have tested it by comment out `type <- match.arg(type)` and it works to accept passing `type="joint"`.

**Comment by KlausVigo** [comment]
Thanks for letting me know. Done
https://github.com/KlausVigo/phangorn/commit/c19ba4ab765487b585ba4adf73bf707398cb68f7
