### ISSUE TITLE
Different results from modelTest() with the same input file

### ISSUE THREAD

**Issue by TMAdams** [KlausVigo/phangorn#141]
Hi Klaus,

I've been working with a phylogeny that contains some branches with very low support values and have noticed that different runs of the tree building will produce different results.

Whilst this isn't necessarily a concern, whilst backtracking to diagnose when the changes came in, I noticed that the results of modelTest() were slightly different every time it was run despite using the same input files and parameters.

Is this expected behaviour? From my reading of the documentation I wasn't expecting there to be stochastic elements at this step.

Many thanks,
Tom

Example outputs from modelTest() with the same inputs and parameters:
> mt_clean_pars_new
        Model   df    logLik      AIC      AICw AICc AICcw      BIC
1         JTT 5129 -195280.9 400819.9 0.0000000  NaN   NaN 418942.6
2       JTT+I 5129 -195280.9 400819.9 0.0000000  NaN   NaN 418942.6
3    JTT+G(4) 5130 -191143.3 392546.7 0.7349543  NaN   NaN 410672.9
4  JTT+G(4)+I 5131 -191143.4 392548.7 0.2650457  NaN   NaN 410678.5
5          LG 5129 -200080.0 410417.9 0.0000000  NaN   NaN 428540.7
6        LG+I 5129 -200080.0 410417.9 0.0000000  NaN   NaN 428540.7
7     LG+G(4) 5130 -195369.9 400999.9 0.0000000  NaN   NaN 419126.2
8   LG+G(4)+I 5131 -195369.9 401001.9 0.0000000  NaN   NaN 419131.7
9         WAG 5129 -196783.1 403824.1 0.0000000  NaN   NaN 421946.9
10      WAG+I 5129 -196783.1 403824.1 0.0000000  NaN   NaN 421946.9
11   WAG+G(4) 5130 -193273.2 396806.4 0.0000000  NaN   NaN 414932.7
12 WAG+G(4)+I 5130 -193273.2 396806.4 0.0000000  NaN   NaN 414932.7
> mt_clean_pars_old
        Model   df    logLik      AIC      AICw AICc AICcw      BIC
1         JTT 5129 -195346.6 400951.3 0.0000000  NaN   NaN 419074.0
2       JTT+I 5129 -195346.6 400951.3 0.0000000  NaN   NaN 419074.0
3    JTT+G(4) 5130 -191215.7 392691.3 0.7411509  NaN   NaN 410817.6
4  JTT+G(4)+I 5131 -191215.7 392693.4 0.2588491  NaN   NaN 410823.2
5          LG 5129 -200202.0 410662.0 0.0000000  NaN   NaN 428784.7
6        LG+I 5129 -200202.0 410661.9 0.0000000  NaN   NaN 428784.7
7     LG+G(4) 5130 -195490.2 401240.4 0.0000000  NaN   NaN 419366.7
8   LG+G(4)+I 5131 -195490.2 401242.3 0.0000000  NaN   NaN 419372.1
9         WAG 5129 -196894.6 404047.2 0.0000000  NaN   NaN 422169.9
10      WAG+I 5129 -196894.6 404047.2 0.0000000  NaN   NaN 422169.9
11   WAG+G(4) 5130 -193391.0 397042.0 0.0000000  NaN   NaN 415168.2
12 WAG+G(4)+I 5130 -193391.0 397042.0 0.0000000  NaN   NaN 415168.2
> mt_clean_pars <- readRDS("results/intermediate/mt_clean_pars.rds")
> mt_clean_pars
        Model   df    logLik      AIC      AICw AICc AICcw      BIC
1         JTT 5129 -195267.5 400793.1 0.0000000  NaN   NaN 418915.8
2       JTT+I 5129 -195267.5 400793.1 0.0000000  NaN   NaN 418915.8
3    JTT+G(4) 5130 -191112.8 392485.6 0.7320457  NaN   NaN 410611.9
4  JTT+G(4)+I 5131 -191112.8 392487.6 0.2679543  NaN   NaN 410617.4
5          LG 5129 -200080.9 410419.9 0.0000000  NaN   NaN 428542.6
6        LG+I 5129 -200080.9 410419.9 0.0000000  NaN   NaN 428542.6
7     LG+G(4) 5130 -195359.8 400979.6 0.0000000  NaN   NaN 419105.9
8   LG+G(4)+I 5131 -195359.8 400981.6 0.0000000  NaN   NaN 419111.4
9         WAG 5129 -196778.7 403815.3 0.0000000  NaN   NaN 421938.1
10      WAG+I 5129 -196778.6 403815.3 0.0000000  NaN   NaN 421938.0
11   WAG+G(4) 5130 -193257.7 396775.3 0.0000000  NaN   NaN 414901.6
12 WAG+G(4)+I 5130 -193257.7 396775.3 0.0000000  NaN   NaN 414901.6

**Comment by KlausVigo** [comment]
Hi @TMAdams, 
is it possible to send me your data and the code you used for this example?
Kind regards, 
Klaus

**Comment by TMAdams** [comment]
Of course, is there a preferred email address for you I should use?

**Comment by KlausVigo** [comment]
Hi @TMAdams, 
use klaus.schliep@gmail.com. 
There is some stochastic element in it. If no tree is supplied modelTest uses a random addition tree, as these are often better than distance based trees and also pretty fast. So if your data set has many low support edges it is very likely the random addition tree gets stuck in a local optimum. I will change this use just a few starting trees, that should reduce the variation a lot. 
The question important for modelTest is does the input tree change the order of the (best) AIC / BIC values? So that's why it is useful to test it on a set of different data set.      
Thanks for spotting this, I will also update the help page to make users aware of this.
Kind regards, 
Klaus

**Comment by TMAdams** [comment]
Thanks Klaus, have emailed you. It likely was some low support edges, these do move around in repeats of the tree and have very low bootstrap values after 1,000 reps.

The BIC ordering didn't change, it seemed like only the absolute values did.

Thanks for your quick response!
Tom
