### ISSUE TITLE
Unable to load module "Fitch_mod": vector is too large

### ISSUE THREAD

**Issue by mdhall272** [KlausVigo/phangorn#145]
I can't load phangorn as of today (R 4.2.2, MacOS 13) due to the following error:

```
> library(phangorn)
Loading required package: ape
Error: package or namespace load failed for ‘phangorn’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package phangorn: loadModule(module = "Fitch_mod", what = TRUE, env = ns, loadNow = TRUE): Unable to load module "Fitch_mod": vector is too large
```

I've tried `remove.packages` on phangorn and reinstalling it clean, to no avail.

**Comment by KlausVigo** [comment]
Hi @mdhall272,
I haven't seen this error and I don't use MacOS so I only can speculate. First you want to check that also Rcpp is properly installed. During installation did you compile the package from source or did you installed it as a binary or using a tool like Anaconda?

**Comment by mdhall272** [comment]
It does work when installed from source, as it turns out. Sorry, I was a bit tired last night.

**Comment by KlausVigo** [comment]
Good, that it worked out.
