### ISSUE TITLE
densiTree not working

### ISSUE THREAD

**Issue by Cosmophasis** [KlausVigo/phangorn#146]
Hi Klaus,

I am trying to plot a DensiTree with my species tree output from StarBEAST2. I use read.nexus to read my trees and then use the trees as x in densiTree. The output shows the tip labels and the time axis but there's no trees. 

I have attached a file for your reference.
[Geo_star_eupa2_species.txt](https://github.com/KlausVigo/phangorn/files/11010197/Geo_star_eupa2_species.txt)

Thanks in advance,
Colin

**Comment by KlausVigo** [comment]
Dear Colin, 
you have 1001 trees, so you might want to change the parameter alpha (opacity) to a larger value and also increase the line width so that the chance that are lines are plotted on top of each other. E.g. try 
`densiTree(x, width = 5, alpha=.01)`
Kind regards, 
Klaus

**Comment by Cosmophasis** [comment]
Hi Klaus,
Thanks for the quick response. For some reason it works perfectly fine now with the default parameters. 
Thanks again,
Colin
