### ISSUE TITLE
write.phyDat Problem

### ISSUE THREAD

**Issue by ChristophKnapp** [KlausVigo/phangorn#150]
Hi, given that this issue hasn't come up yet, its probably something I'm doing wrong. I tried the tutorial from [https://rdrr.io/github/KlausVigo/phangorn/man/read.phyDat.html](https://rdrr.io/github/KlausVigo/phangorn/man/read.phyDat.html) and tried to retrieve the sequences of the nodes. With the primates phyDat Object everything is fine but with the phyDat Objects generated by ancestral.pars (or any other method I tried) , the data is wrong. When I try to write the nodes to fasta file an exception occurs. I pasted some code below. 

```
fdir <- system.file("extdata/trees", package = "phangorn")
primates <- read.phyDat(file.path(fdir, "primates.dna"),
                        format = "interleaved")
tree <- pratchet(primates, trace=0) |> acctran(primates)
parsimony(tree, primates)

anc.acctran <- ancestral.pars(tree, primates, "ACCTRAN")
anc.mpr <- ancestral.pars(tree, primates, "MPR")

tmp = as.data.frame(primates)
tmp = as.data.frame(anc.acctran) # wrong data frame
tmp = as.data.frame(anc.mpr) # wrong data frame

write.phyDat(primates, file = "~/test1.fasta", format = "fasta") # works 
write.phyDat(anc.acctran, file = "~/test2.fasta", format = "fasta") # throws exception
#Error in result[i, ] <- labels[x[[i]]] : 
#  number of items to replace is not a multiple of replacement length
write.phyDat(anc.mpr, file = "~/test3.fasta", format = "fasta") # throws exception
#Error in result[i, ] <- labels[x[[i]]] : 
#  number of items to replace is not a multiple of replacement length
```

Regards

**Comment by KlausVigo** [comment]
Dear @ChristophKnapp,
try 
```
anc.acctran <- ancestral.pars(tree, primates, "ACCTRAN", return = "phyDat")
anc.mpr <- ancestral.pars(tree, primates, "MPR", return = "phyDat")
``` 
I will change the function and output to be easier the use.

Kind regards, 
Klaus

**Comment by ChristophKnapp** [comment]
Dear Klaus

Thank you for your fast reply. That works. 

Just to let you know, the next step 

```
seqLogo( t(subset(anc.mpr, getRoot(tree), 1:20)[[1]]), ic.scale=FALSE)
#Error in makePWM(pwm) : PWM for DNA motifs must have 4 rows
```
Gives an error now.

And 
```
plotAnc(tree, anc.mpr, 17)
#Error in pie[i, ] : subscript out of bounds
#In addition: Warning message:
#In matrix(unlist(y[]), ncol = nc, byrow = TRUE) :
#  data length [26] is not a sub-multiple or multiple of the number of rows [7] 
```
plots the tree but it has problems with the pie charts now.

For that to work, I have to change back to ```return = "prob"``` in the above function.

The reason I got confused was, in the help for the ancestral.pml {phangorn} function, it says:

"return     return a phyDat object or matrix of probabilities."

but both parameters return a phyDat object with different content or purpose. 

Sorry for being a pain. Phangorn is a very good package. 

Kind Regards
 
Christoph

**Comment by KlausVigo** [comment]
Dear Christoph, 

I started changing the underlying code a bit and I hope it works more straight forward now.
`ancestral.pars` returns now an object of class `ancestral` by default to distinguish them (and additional also class `phyDat`, but this might drop later). This can be plotted and you can transform it to a `data.frame` containing the probabilities. 
You can also transform it to a proper`phyDat` object, but you might loose information if data are not nucleotide sequences and you used parsimony. `plotAnc`  now also accepts `phyDat` objects. 
You might want to try the version on github and tell me if you find further oddities.

Regards, 
Klaus  

PS: I still have to update the man pages and the vignette.
