### ISSUE TITLE
modelTest seems to require additional inputs

### ISSUE THREAD

**Issue by Phylloxera** [KlausVigo/phangorn#152]
R 4.3.1 on Mac.
input is a small alignment of 5 16s partial sequences
`library(DECIPHER); dna2 <- DNAStringSet(rownames(clusters)[which(clusters[, 1]==2)]); al5 <- AlignSeqs(dna2)` 
sample code from [trees vignette](https://cran.r-project.org/web/packages/phangorn/vignettes/Trees.html)
`library(ape); library(phangorn); mt <- modelTest(al5)`
`Error in if (attr(data, "type") == "DNA") type <- .dnamodels : 
  argument is of length zero`
maybe something is wrong with my alignment?

**Comment by Phylloxera** [comment]
ok. mistake 1 was not inputing as phangorn phyDat class. new code
`al5 <- phyDat(as(al5, "matrix"), type="DNA"); class(al5); mt <- modelTest(al5)`
new error
`Error in fit.sankoffNew(tree, data, cost, returnData = site) : 
  INTEGER() can only be applied to a 'integer', not a 'NULL'`

**Comment by KlausVigo** [comment]
Hi @Phylloxera!
 Can you test if the error appears still with the development version? You can get binaries for the Mac from https://klausvigo.r-universe.dev/phangorn. And if not can you send me the data?

**Comment by Phylloxera** [comment]
Looks like I can't validate on Mac. Probably a positive reflection on my employer's security protocols.
`Error: package or namespace load failed for ‘phangorn’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/aaron.dickey/Library/R/x86_64/4.3/library/phangorn/libs/phangorn.so':
  dlopen(/Users/aaron.dickey/Library/R/x86_64/4.3/library/phangorn/libs/phangorn.so, 0x0006): tried: '/Users/aaron.dickey/Library/R/x86_64/4.3/library/phangorn/libs/phangorn.so' (code signature in <4B8D6B85-529A-31C4-90E5-6DBC9CA67F31> '/Users/aaron.dickey/Library/R/x86_64/4.3/library/phangorn/libs/phangorn.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/aaron.dickey/Library/R/x86_64/4.3/library/phangorn/libs/phangorn.so' (no such file), '/Users/aaron.dickey/Library/R/x86_64/4.3/library/phangorn/libs/phangorn.so' (code signature in <4B8D6B85-529A-31C4-90E5-6DBC9CA67F31> '/Users/aaron.dickey/Library/R/x86_64/4.3/library/phangorn/libs/phangorn.so' not valid for use in process: library load disallowed by system` The data is small enough, you should be able to confirm with the attached [alignment](https://github.com/KlausVigo/phangorn/files/13116847/al5.rds.zip)

**Comment by KlausVigo** [comment]
It seems your alignment is missing names. `names(al5)`  seems empty.

**Comment by Phylloxera** [comment]
Hmmm. Thinking that was the source of the second error all along. Evidently, `DECIPHER::AlignSeqs()` lets users do that.
In that case, the second error is most likely the fault of me not following @benjjneb [published workflow](https://f1000research.com/articles/5-1492) since assigning names prior to creating the alignment is there plain as day.
Closing.
