### ISSUE TITLE
R is crashed when loading a phangorn library

### ISSUE THREAD

**Issue by trilisser** [KlausVigo/phangorn#154]
Hi there. During phangorn library loading R (or R stiduo) is crashed and a session is restarted.

R version 4.2.2

```
packageVersion("phangorn")
[1] ‘2.11.1’
```

**Comment by KlausVigo** [comment]
Which operating system are you using? Is it working if you use just R and not RStudio?

**Comment by trilisser** [comment]
Sorry. I used Windows 10 Pro.
During installation it gives a warning:
>WARNING: Rtools is required to build R packages but is not currently installed. 
>Please download and install the appropriate version of Rtools before proceeding:

But Rtools is installed (as I remember). I tried to install new version of Rtools and reinstall `phangorn` but it doesn't work.

**Comment by KlausVigo** [comment]
Maybe try the binaries from https://klausvigo.r-universe.dev/phangorn#

**Comment by trilisser** [comment]
Thank you for your answers.
I solved the problem by installing `Rtools` in a default folder `C:\Rootls`. After that, `phangorn` is launched well!

**Comment by KlausVigo** [comment]
@trilisser, good to hear that it worked.
