### ISSUE TITLE
Please use `make_graph` instead of `graph`

### ISSUE THREAD

**Issue by szhorvat** [KlausVigo/phangorn#164]
Please use the documented `igraph::make_graph` instead of the undocumented `igraph::graph` which is not guaranteed to stay around for long.

https://github.com/KlausVigo/phangorn/blob/91439ab236b7b367ab51e7ddceba2c31f3e26562/NAMESPACE#L298

**Comment by KlausVigo** [comment]
Hi @szhorvat, 
thanks or pointing this out.  Should be fixed now.
