### ISSUE TITLE
The 'i' argument in 'plotAnc' does not act as described in doc

### ISSUE THREAD

**Issue by qifei9** [KlausVigo/phangorn#17]
The doc of `ancestral.pml` says:
```
i: plots the i-th character of the ‘data’.
```
However, I found it actually plots the i-th site pattern of the 'data'.

**Comment by KlausVigo** [comment]
@qifei9 thanks for spotting. fixed and added a small example 
https://github.com/KlausVigo/phangorn/commit/992055da79f0a730c69e489c24b04afb28dc9785
I will change this in future to be more intuitive.
