### ISSUE TITLE
'Error in INDEX[i, ]: subscript out of bounds' when optimizing tree topology

### ISSUE THREAD

**Issue by qifei9** [KlausVigo/phangorn#18]
I got `Error in INDEX[i, ]: subscript out of bounds` when optimizing tree topology using `optim.pml` for some trees.

code:
```
data <- read.phyDat("./group_0001802_aligned_phylip.txt", format = 'phylip', type = 'DNA')
dm <- dist.ml(data)
tree <- NJ(dm)
fit <- pml(tree, data)
fit <- optim.pml(fit, rearrangement = 'stochastic')
```
The error occurs when `rearrangement='stochastic'`, `NNI` or `ratchet`. When `rearrangement='none'`, it is fine.

Info:
```
Archlinux
R version: 3.3.3 (2017-03-06)
phangron: installed from github
```

Data:
[group_0001802_aligned_phylip.txt](https://github.com/KlausVigo/phangorn/files/856146/group_0001802_aligned_phylip.txt)

**Comment by KlausVigo** [comment]
@qifei9 thanks again. https://github.com/KlausVigo/phangorn/commit/66d65de5be0f61547efb9af4b157cdd95f9cc64c fixes this issue. Problem was that there are only 3 unique sequences and therefore tree rearrangements are not necessary. The other sequences can be added as multifurcations with zero edge length to the tree.

**Comment by qifei9** [comment]
When an alignment have only 3 unique sequences, i.e. `any(dup)` is `FALSE`, this error still occurs. Perhaps the check of `length(tree$tip.label) < 4` should be moved out the chunk of `if (any(dup))`.

**Comment by KlausVigo** [comment]
Thanks again @qifei9. Put it outside the `if(any(dup))`
