### ISSUE TITLE
modelTest failing with relatively small alignment

### ISSUE THREAD

**Issue by hettling** [KlausVigo/phangorn#2]
Dear KlausVigo,
we are happily using phasngorn's `modelTest` for a large amount of data, which works well for most cases.
However, I encountered errors with some alignments, I posted an example here: https://raw.githubusercontent.com/naturalis/supersmart/master/t/testdata/modeltest-aln.fa

I could narrow it down a bit, the error occurs when testing for the GTR model:
`test <- modelTest(phyDat(data), model = "GTR")`

More specifically, I get an error `Error: NA/NaN/Inf in foreign function call (arg 1)` when optimizing the gamma parameter (call of `optim.pml`, https://github.com/KlausVigo/phangorn/blob/master/R/phylo.R#L349-350).

I couldn't get further than that, I would greatly appreciate if you could help me!

Regards, Hannes

**Comment by KlausVigo** [comment]
Dear Hannes, 
which version of phangorn, operating system are you using? I made in the last version some improvements. Works on my linux machine with the latest CRAN and development version, maybe try:
`devtools::install_github("KlausVigo/phangorn")`
Of course with this small data sets there is always the problem that some transitions or transversion do not appear in your data and GTR has problems to estimate them (here a <-> t is extremely low). 

```
(mT <- modelTest(data))
env = attr(mT, "env")
(GTR <- get("GTR+G+I", env)) 
eval(GTR, env=env)

 loglikelihood: -557.1203 

unconstrained loglikelihood: -783.0539 
Proportion of invariant sites: 4.68329e-05 
Discrete gamma model
Number of rate categories: 4 
Shape parameter: 0.3674263 

Rate matrix:
             a         c        g            t
a 0.000000e+00 0.9881062 2.931997 1.928358e-06
c 9.881062e-01 0.0000000 3.612297 4.762684e+00
g 2.931997e+00 3.6122969 0.000000 1.000000e+00
t 1.928358e-06 4.7626837 1.000000 0.000000e+00

Base frequencies:  
0.3785028 0.1736592 0.1444078 0.3034302 
 ```

Regards, 
Klaus

**Comment by hettling** [comment]
Dear Klaus,

yes, the github version seems to work fine! I had the cran version of phangorn:

phangorn_1.99-12
ape_3.2 
R version 3.0.2 
Platform: x86_64-pc-linux-gnu

I could have checked the newest version before I posted an issue, my apologies for that. 

Many thanks for your help,

Regards

Hannes
