### ISSUE TITLE
How to extract ancestral sequence to character or DNAbin?

### ISSUE THREAD

**Issue by Ward9250** [KlausVigo/phangorn#24]
Hi,

I've done a test ancestral reconstruction with some mouse data:

```R
library(ape)
library(phangorn)
data(woodmouse)

w <- as.phyDat(woodmouse)

tree <- pratchet(w, trace=0)
tree <- acctran(tree, w)

anc.acctran <- ancestral.pars(tree, w, "ACCTRAN")
```

How to I extract the sequences from anc.acctran as say a character matrix or DNAbin?
as.DNAbin and as.character are not working for me:

```R
> as.DNAbin(anc.acctran)
Error in as.DNAbin.phyDat(anc.acctran) : 
  number of items to replace is not a multiple of replacement length
> as.character(anc.acctran)
Error in as.character.phyDat(anc.acctran) : 
  number of items to replace is not a multiple of replacement length
```

The reason for wanting this is I'm trying to generate a root sequence to use in the simSeq method.

Thanks,
Ben.

**Comment by KlausVigo** [comment]
Hi @Ward9250, 
try
```
anc.acctran <- phangorn:::ancestral2phyDat(anc.acctran)
as.DNAbin(anc.acctran) 
```
At the moment `ancestral.pars` returns a probabilities instead of the most likely state. The helper function `phangorn:::ancestral2phyDat` just does this. I will try to get a more intuitive solution soonish. 
Best
Klaus
