### ISSUE TITLE
modelTest stalled 

### ISSUE THREAD

**Issue by hettling** [KlausVigo/phangorn#3]
Dear Klaus,
in our dataset of alignments, I found some more alignments which cause trouble for phangorn's `modelTest`. I posted an example on our project page: https://raw.githubusercontent.com/naturalis/supersmart/master/t/testdata/modeltest-aln.fa

Running

    require('phangorn')
    dna <- read.FASTA("modeltest-aln.fa")
    tree <- read.tree(text="((9541:0.529608,9544:0.529608):32.270392,9606:32.800000):44.700000;")
    dat <- phyDat(dna, type="DNA")
    test <- modelTest(dat, tree=tree)

`modelTest` never returns, it looks to me like it maybe gets stuck in some local optimum while optimizing for the `GTR+G` model.

For some of our alignments, I get it to run by changing some parameter values, for instance `k=6` instead of `k=4`. We would however like to use `modelTest` as part of a pipeline for large datasets, so playing around with parameter values for each alignment is not really an option. 

The fact that no error is given and I have to kill the entire R process when `modelTest` stalls makes it difficult to automate in our pipeline.

If you could suggest some way how to deal with it, I would be very happy.

Many thanks and Best Regards

Hannes

**Comment by hettling** [comment]
I forgot to mention, this time I am using the newest GitHub version, here is my `sessionInfo()`:

    R version 3.2.0 (2015-04-16)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04 LTS

     locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
     [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] phangorn_1.99-14 ape_3.2         

    loaded via a namespace (and not attached):
    [1] Matrix_1.2-0    nnls_1.4        parallel_3.2.0  igraph_0.7.1   
    [5] nlme_3.1-120    grid_3.2.0      lattice_0.20-31 quadprog_1.5-5

**Comment by KlausVigo** [comment]
Dear Hannes, 

seems with this data set was a problem with the edge length of the supplied tree. They were too long (~100x). This seem to prevented the optimisation didn't work properly and than probably caused some numerical under/overflow.
I am now estimate the edge length with non negative least squares. This should give valid starting values for the optimisation routine. 
I also increased the default for the number of iterations, so `modelTest` may takes a bit longer to run. 

Regards, 
Klaus

**Comment by hettling** [comment]
Dear Klaus,

thanks a lot! The example posted above works fine now, I am now running modelTest for my whole dataset over the weekend, hope it will work for all my alignments!
