### ISSUE TITLE
Cannot resolve .Call("invSites")

### ISSUE THREAD

**Issue by ndukler** [KlausVigo/phangorn#34]
Depending on the order in which I source some external scripts I get this message when trying to run pml(). 

Error in .Call("invSites", data, as.integer(nr), as.integer(nc), contrast,  (from treeFunctions.R#65) : 
  "invSites" not resolved from current namespace (phangorn)

My guess is this could be resolved by adding PACKAGE='phangorn' to the .Call() function calls (ie.  .Call("invSites", data, as.integer(nr), as.integer(nc), contrast,,PACKAGE='phangorn' )). I've tried to clone phangorn and test this but then I get the error:

Error : objects ‘has.singles’, ‘reorderRcpp’ are not exported by 'namespace:ape'

when trying to rebuild the package.  Here is my session info:

R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.6 (Santiago)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] ape_4.1

loaded via a namespace (and not attached):
[1] parallel_3.3.3  nlme_3.1-131    grid_3.3.3      lattice_0.20-35

**Comment by KlausVigo** [comment]
Hi @ndukler, 
the development version of phangorn needs the development version of ape. See http://ape-package.ird.fr/ape_installation.html and also https://www.mail-archive.com/r-sig-phylo@r-project.org/msg05090.html how to install it.
