### ISSUE TITLE
error in neighborNet function

### ISSUE THREAD

**Issue by natagalle** [KlausVigo/phangorn#37]
Hello 

I´ve been trying to tun the example given in the neighborNet function

data(yeast)
dm <- dist.ml(yeast)
nnet <- neighborNet(dm)
plot(nnet, "2D")

But after running the function I get this error:

> nnet <- neighborNet(dm)
Error in quadprog::solve.QP.compact(as.matrix(Dmat), as.vector(dvec),  : 
  object '.QP_aind' not found

Thanks,

N.

**Comment by KlausVigo** [comment]
Dear @natagalle, 

can you send the output of `sessionInfo()`. I may be a platform dependent problem or that the `quadprog` package is not properly installed. 

Cheers, 
Klaus

**Comment by natagalle** [comment]
Dear @KlausVigo 

Thank you very much for your fast reply. You were right! I reinstalled the quadprog package, and now the function is running.

Thanks!

N.

**Comment by ayala-usma** [comment]
Does phangorn include any kind of dependency verification step? I stumbled upon this issue today and it seems that I didn't even had the quadprog package installed, but phangorn never threw a warning when I was installing it. Could this feature be included in upcoming versions?

**Comment by KlausVigo** [comment]
Hi @ayala-usma , 
this is not a problem with `phangorn`. Usually if you install it from CRAN it should install all dependencies. Did you install phangorn from github? I am not sure if `install_github` for example does this. 
Cheers, 
Klaus

**Comment by ayala-usma** [comment]
I installed it first via CRAN repository, and then used the install_github() to update to the most recent development version. Since I solved the problem by installing manually the quadprog package, I assume there was no dependency resolution even from the CRAN repo. :S

**Comment by KlausVigo** [comment]
Hi @ayala-usma,
 there should be for CRAN. Maybe your defaults are set wrong or for R 3.5 all packages needed to be reinstalled, this may not worked properly. I would see this a problem with `install.packages` or `install_github`. I will reopen the issue it if there are more complaints.
