### ISSUE TITLE
Retrieving positions of site patterns in PhyDat

### ISSUE THREAD

**Issue by rprops** [KlausVigo/phangorn#39]
Hi,

I was wondering if there was a way (eg, accessor function, attribute) to retrieve the exact positions in the alignment of the different site patterns stored in the phyDat objects.
For example:  

```
> test_phydat
4 sequences with 1776 character and 148 different site patterns.
The states are a c g t 
```

In this case I would like to retrieve the positions in the alignment of the 148 site patterns.

Thank you,

Ruben

**Comment by KlausVigo** [comment]
Hi @rprops , 
you should be able get the positions with `attr(test_phydat, "index")`. 
Cheers, 
Klaus
