### ISSUE TITLE
simSeq: predict number of mutated nucleotides

### ISSUE THREAD

**Issue by richelbilderbeek** [KlausVigo/phangorn#42]
Hi Klaus,

I have trouble predicting the number of mutated nucleotides by `simSeq`. Do you have a pointer to the tool `simSeq` is based on, or the article you've used?

Sure, I could put my code here, but I assume I am wrong and am overlooking something...

**Comment by richelbilderbeek** [comment]
Ah, I read in [1] that `simSeq` is based on Seq-Gen [2]. 

May I suggest to add this to the documentation?

 * If yes, I volunteer to do so.
 * If no, that is just as fine, people can find the answer now here :-)

## References

 * [1] Paradis, Emmanuel. Analysis of Phylogenetics and Evolution with R. Springer Science & Business Media, 2011. Chapter 4.7 Molecular sequences
 * [2] Rambaut, Andrew, and Nicholas C. Grass. "Seq-Gen: an application for the Monte Carlo simulation of DNA sequence evolution along phylogenetic trees." Bioinformatics 13.3 (1997): 235-238.

**Comment by KlausVigo** [comment]
Hi @richelbilderbeek , 
the algorithm used to compute sequences in `simSeq` should be very similar to Seq-Gen, but  `simSeq` does not use Seq-Gen internally.
 The number of expected mutations / transitions per site is the sum of the edge length of the tree (assuming that the rate is 1, which is a usual convention). I only simulate the states for each node of the tree not the number of mutations. 
Cheers, 
Klaus

**Comment by richelbilderbeek** [comment]
Hi @KlausVigo, thanks for your reply!

Yes, I've confirmed the number of mutations matches those of Seq-Gen. If you want, I can add this as a test to your test suite (which would also increase your code coverage). If yes, you can create a new issue and assign/mention me. 

In any case, I think this issue can be closed after you reading this.

Keep up the good work :+1:
