### ISSUE TITLE
Converting phyDat instance to a dataframe

### ISSUE THREAD

**Issue by halabikeren** [KlausVigo/phangorn#44]
Dear Klaus,

I wish to convert a phyDat instance to a dataframe, where each row denotes a taxon and each column denotes a (non unique) site pattern in the alignment.

Currently, I'm using a method that extracts only the unique site patterns, like so:

```
convertPhyDatToDF <- function(data, states_translator) {
  df = data.frame(t(sapply(data,c)))
  ndf <- data.frame(lapply(df, function(i) states_translator[i]))
  return(data.frame(t(ndf)))
}

```
Could you please guide me how to duplicate each site pattern according to its number of its appearances in the original alignment?

Many thanks!
Keren

**Comment by KlausVigo** [comment]
Dear Keren, 
there is a `as.data.frame` method for `phyDat` objects. 

```
> library(phangorn)
> data(Laurasiatherian)
> Laurasiatherian
47 sequences with 3179 character and 1605 different site patterns.
The states are a c g t 
> tmp <- as.data.frame(Laurasiatherian)
> dim(tmp)
[1] 3179   47
```
You probably want to transpose this. 

There are quite a few methods already available for phyDat objects:
```
> methods(class = phyDat)
 [1] as.AAbin             as.character         as.data.frame        as.DNAbin            as.MultipleAlignment c                   
 [7] cbind                image                print                subset               unique              
see '?methods' for accessing help and source code
```
I have to check if I actually export all the methods which are available. 

Regards, 
Klaus
