### ISSUE TITLE
simSeq: write tests 

### ISSUE THREAD

**Issue by KlausVigo** [KlausVigo/phangorn#46]
Hi @richelbilderbeek, 
thanks for volunteering. Writing tests to verify that `simSeq` works like Seq-Gen produces the right number of mutations and expected site patterns. 
Thanks, 
Klaus

**Comment by richelbilderbeek** [comment]
Awesome! Will put the code I wrote to do exactly that on `devel` with a Pull Request this Saturday. Thanks for letting me help.
