### ISSUE TITLE
error in KF.dist and path.dist functions: object "phy" not class "phylo"

### ISSUE THREAD

**Issue by HernanVM** [KlausVigo/phangorn#47]
I am trying to calculate the KF and path distances for a multiPhylo object (1000 simulations) created by phytools' pbtree function with 26 tips. I unfortunately get this error:

```
N <- 26
simtrees<-pbtree(n=N,nsim=1000)

simKF <- KF.dist(simtrees, tree2=NULL, check.labels=TRUE, rooted=FALSE)
Error in is.rooted(trees) : object "phy" is not of class "phylo"
simPD <- path.dist(simtrees, tree2=NULL, check.labels=TRUE, use.weight=FALSE)
Error in unroot(trees) : object "phy" is not of class "phylo"
```

From the following you can see that my simtrees object should be appropriate. I used phytools multiRF function on that simtrees object and obtained the RF distance matrix no problem.

```
head (simtrees)
6 phylogenetic trees
class(simtrees)
[1] "multiPhylo"
simRF <- multiRF(simtrees)
Some trees are rooted. Unrooting all trees.
```

Thank you,

Hernán

**Comment by KlausVigo** [comment]
Dear Hernan, 
I cannot reproduce the error. 
Try to unroot the trees before using `RF.dist`. 
`simtrees <- unroot(simtrees)` 
Maybe you can check that you have recent version of ape (5.1), phangorn & phytools installed and add the output of `sessionInfo()`.

**Comment by HernanVM** [comment]
Hello Klaus,

I was indeed using older versions. I tried upgrading to current phangorn and phytools versions but ape 5.1 is not available for my old R3.1, and the installs left me with defaults.
```
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] phangorn_1.99-12 phytools_0.4-56  maps_2.3-9       ape_3.4
```
I went on an installed R3.5 with Rswitch and that allowed me install all correct versions. Thank you.

- Hernán
