### ISSUE TITLE
read.phyDat: Processing sequence data with numerical states

### ISSUE THREAD

**Issue by halabikeren** [KlausVigo/phangorn#49]
Dear Klaus,

Is it possible to process a fasta file in which the states are numerical? 

For example, providing a fasta file with the following content to `read.phyDat` as follows:
```
>S1
0
>S2
0
>S3
1
>S4
1
```
`char_data =  read.phyDat(char_data_path, format="fasta", type="USER", levels=c("0","1"), drop.unused.levels=FALSE)`

Yields:
```
Error in `row.names<-.data.frame`(`*tmp*`, value = as.character(1:p)) : 
  invalid 'row.names' length
```

Many thanks!
Keren

**Comment by KlausVigo** [comment]
Hi @halabikeren,  
should work now again for fasta file commit d71e703825954e2e4760ffb434740e5c76d52a02.
