### ISSUE TITLE
Odd behavior in fitch()

### ISSUE THREAD

**Issue by wrightaprilm** [KlausVigo/phangorn#58]
Hi Klaus,

I'm writing a little Rackage [for teaching](https://github.com/wrightaprilm/treesiftr). In the worked example in the README, I generate 10 plots and annotate them with parsimony + L scores. But a couple of the p_scores look wrong. I attached one below, for two characters (uncolored lines = missing data, brown = 1, blue=0).  Am I overlooking something in how the p_scores are calculated? 

![example](https://user-images.githubusercontent.com/1715446/43336459-99a87a7c-9196-11e8-951c-02c2b17b34b9.png)

**Comment by KlausVigo** [comment]
Hi April, 
should be fixed with the pull request to treesiftr.
