### ISSUE TITLE
SimSeq(): Generating DNA sequences without a tree

### ISSUE THREAD

**Issue by jphill01** [KlausVigo/phangorn#59]
Hello,

I am looking to simulate some DNA sequences under a given substitution model (e.g, JC69, K80) without specifying a tree. Instead, one would specify (1) the number of sequences to generate, (2) the length of sequences to generate, and (3) a forward mutation rate (or some other quantities).

Is it possible to easily modify source code for simSeq() to accomplish this?

Thanks.

**Comment by KlausVigo** [comment]
Hi @jphill01, 
I am not sure if `simSeq()` is what you want. When you simulate events / mutations you have (at least) two options. You have predefined intervals (nodes in a tree) and you compute what the sequence would look like on each grid point. If the intervals are too small you don't have any change in your sequence, if too long you may have multiple changes and some of these may be hidden for you.    
Here is some code to simulate time series of sequences sampled at fixed interval. We just ignore the second tip.  
```
library(phangorn)
tree <- stree(21, "right") # choose how many time points you want to sample
tree <- drop.tip(tree, 2:20, collapse.singles = FALSE)
tree$edge.length <- rep(.1, nrow(tree$edge)) 
# some edge length
# defines the transition probability
# if you simulate more sequences you want smaller intervals  

plot(tree)
nodelabels()
tiplabels()

dat <- simSeq(tree, ancestral = TRUE, l=3)
as.character(dat)[c(3:22,1),] # reorder from root to tip
```
rows in `dat` are time points (size of the tree), columns are loci (`l` parameter in `simSeq`)
transition probabilities: P(t) = exp(Qt), 
if you increase the `edge.length` you will have more changes, as mutation rate is multiplied with time. (You change the time here and not the rate, but that does not matter) 

You can also sample waiting times to the next event (event) and so each sequence you sample will be different, which maybe more what you are up to. 
 
Cheers, 
Klaus

**Comment by jphill01** [comment]
Thanks Klaus, 

From my searching, every R package I have found requires a phylogeny as input.

I can write some code to generate completely random DNA sequences of a given length, but these are not influenced by any underlying substitution model.

**Comment by KlausVigo** [comment]
Hi Jarrett, 

`"From my searching, every R package I have found requires a phylogeny as input."`
I think that is expected and I will try to explain. What you want is to simulate a new (descendant) sequence `X1` with a substitution model (JC, K80, GTR,...) from another (ancestral) sequence `X0`. We can describe this ancestor descendant relationship with a graph:
`X0 --> X1`
Seems not very useful by itself. 
But you may want to take `X1` to simulate another sequence `X2` from it and so on and we can describe this relationship again as a graph:
`X0 --> X1 --> X2 --> X3 --> X4  ...`
This is what the code in my previous post simulated. 
As an alternative you have one main sequence from which you simulate several others from X0. 
```
      -> X1
    /      
X0 --> X2
    \
      -> X3
```
All the 3 graphs above are also trees (!) in the mathematical sense. You can always represent these relationship with a (phylogenetic, coalescent) tree or mathematical more general with a directed acyclic graph. I think this is actually quite elegant and very flexible and keep in mind that these graphs do not need to be binary trees like most phylogenies. 

Cheers, 
Klaus
