### ISSUE TITLE
Bug: cannot find function concensus

### ISSUE THREAD

**Issue by richelbilderbeek** [KlausVigo/phangorn#65]
Hallihallo @KlausVigo,

Thanks for accepting my Pull Request and fixing the `densiTree` bug!

The test I added indeed work when run (tested on a clone of this repo at the `devel` branch). However, as a user, something goes wrong. I will first show what goes right:

```{r}
# Install newest version
devtools::install_github("KlausVigo/phangorn", branch = "devel")

# Create some trees
tree_1 <- ape::read.tree(text = "((A:2,B:2):1, C:3);")
tree_2 <- ape::read.tree(text = "((A:1,C:1):2, B:3);")
trees <- c(tree_1, tree_2)

# Plotting with a consensus works great
phangorn::densiTree(trees, consensus = LETTERS[1:3])
```

However, plotting with a NULL consensus fails:

```
# Plotting with a NULL consensus fails
phangorn::densiTree(trees)
```

with error message:

```
Error in consensus(tree) : could not find function "consensus"
```

I hope you know what causes this and you can fix it with ease :+1:

Tschuess, @richelbilderbeek

**Comment by richelbilderbeek** [comment]
Ah, found the trick: use `ape::consensus`. I will create a PR for you :1st_place_medal:

**Comment by KlausVigo** [comment]
Hi @richelbilderbeek , 
seems I forgot to import consensus from ape. I have used it in other places, but it seems only to bite here. I added it to the NAMESPACE 89ffa018971aec5e3b1a795678491edb1662d486, so it should fix this problem and prevents to turn up in other places. 
Thanks again, 
Klaus

**Comment by richelbilderbeek** [comment]
Okidokey, thanks :+1:
