### ISSUE TITLE
getClans after midpoint rooting

### ISSUE THREAD

**Issue by manu-kg** [KlausVigo/phangorn#68]
Hi,

I am looking into midpoint rooting a tree generated using IQTREE and then running getClans() on the resulting tree. The function getClans() works normal on the original tree, but generates an error post midpoint rooting. Please find below the code and the error encountered. 

`tree1<-read.tree(text="(ssa16_58_87:0.0181266339,(salp_chr_a:0.0160096841,((otsh_chr_b:0.0097490197,okis_chr_b:0.0095262290)96.9_94:0.0019237513,omyk_chr_b:0.0096196507)100_100:0.0111445672)100_100:0.0031052292,
(((((salp_chr_b:0.0138115305,ssa17_1_31:0.0179669905)94.7_93:0.0029454944,((otsh_chr_a:0.0080903366,okis_chr_a:0.0130926445)100_100:0.0035922901,omyk_chr_a:0.0086554721)100_100:0.0132875035)100_100:0.0048625209,huc_chr_b:0.0242224884)96.7_98:0.0035939466,esox_uniq:0.1453270125)94.6_95:0.0027933889,huc_chr_a:0.0211791541)100_100:0.0058284063);")

plot(tree1)
getClans(tree1)

tree2<-midpoint(tree1, node.labels = "label")
plot(tree2)
getClans(tree2)`

I works fine for the tree1 but generates the error below for tree2.

`> getClans(tree2)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent`

Not sure if I am missing something important. How can I get this sorted ?

Thanks in advance,
Manu

**Comment by KlausVigo** [comment]
Dear @manu-kg,
a simple hack is todelete the node.labels
```
tree2$node.label <- NULL
getClans(tree2)
```
Not nice, but it works. 
Regards, 
Klaus
