### ISSUE TITLE
Internal nodes as returned by ancestral.pars

### ISSUE THREAD

**Issue by ndrubins** [KlausVigo/phangorn#73]
Hi Klaus,

I'd like to plot some additional information about ancestral states as inferred using the `ancestral.pars` function.

For that I'm trying to match between the internal nodes that I get from the `phyDat` object which `ancestral.pars` returns and the internal nodes that I get by converting the `phylo` tree object to a `ggdend` object. So matching between them would give me the `xy` coordinates of the internal nodes with their ancestral states.

e.g. if my `phylo` object is `species.tree` this is how I convert it to a `ggdend` object:
species.dend <- phylogram::as.dendrogram.phylo(species.tree) %>%
  dendextend::hang.dendrogram() %>%
  dendextend::hang.dendrogram(hang = -1) %>%
  dendextend::as.ggdend()

Any idea how to do that? 
What are the node IDs that `phylo` uses?

I can get this from the code using a pull request but thought you might be able to answer this faster than I would going through the code.

Thanks a lot,
Nimrod

**Comment by KlausVigo** [comment]
Hi Nimrod, 

I am not using the dendrogram  or ggdend class. 
The class ggdend class seems miss a identifier for nodes and edges and identifies them via its x and y positions, which seems a more than odd decision. 
  
The node ID's in a phylo object (tree$edge) you get quite easy:  
```
library(ape)
tree <- rcoal(10)
plot(tree)
nodelabels()
tiplabels()
```
`tree$tip.label` corresponds to the first nodes `1:Ntip(tree)` (in the example the first 10).
I hope this helps.  

You maybe want also look into ggtree from bioconductor which also produces nice plots. 

Cheers, 
Klaus

**Comment by ndrubins** [comment]
Thanks a lot,
Nimrod
