### ISSUE TITLE
plotBS alternate or adaptation for 1000 node tree

### ISSUE THREAD

**Issue by alptaciroglu** [KlausVigo/phangorn#76]
Hello,

Don't know if I am at the right place to ask this question. So I apologize for any inconvenience. 

I am having issues plotting a 1000 node phylogenetic tree. The labels are on top of each other when drawn using following partial code:

  ```
dm <- dist.ml(myAlignment, model="JTT")
  tree <- NJ(dm)
  cat('Testing all models ...\n')
  (mt <- modelTest(myAlignment, model="all", multicore=multiCoreBool))
  env <- attr(mt, "env")
  fitStart <- eval(get(mt$Model[which.min(mt$BIC)], env), env)
  fitNJ <- pml(tree, myAlignment, model="JTT", k=4, inv=.2)
  fit <- optim.pml(fitNJ, rearrangement = "stochastic",
                  optInv=TRUE, optGamma=TRUE)
  fit
  bs <- bootstrap.pml(fit, bs=100, optNni=TRUE, multicore=multiCoreBool)
  
  tiff("Tree.tiff", units="px", width=3200, height=3200, res=600)
  plotBS(midpoint(fit$tree), bs, p = 50, type="p")
  dev.off()
```

Is there an alternative to plotBS? I saw ggtree can produce good phylogenetic trees but don't know if it is applicable to bootstrapping. Or alternatively, I can somehow reduce font size.

**Comment by KlausVigo** [comment]
That is always a problem if trees have more than 100 tip labels. Sometimes `type="fan"` spread things out a bit. You can try to play around with the `bs.adj` argument. `ggtree` can plot bootstrap values. 

You can export the tree returned from `plotBS`
```
tree_with_bs_values <- plotBS(midpoint(fit$tree), bs, p = 50, type="p")
write.tree(tree_with_bs_values,  file = "tree.phy")
```
