### ISSUE TITLE
Problems importing tree from Splitstree

### ISSUE THREAD

**Issue by ywx1** [KlausVigo/phangorn#81]
I have a nexus file which I opened and subsequently saved on Splitstree. I have therefore confirmed that this file can be read by Splitstree. 
However, when I tried to open it using phangorn in R, I am unable to. I have tried the read.nexus.networx command, but it gives me the error "NAs introduced by coercion". Opening it by read.nexus gives me Error in start:end : argument of length 0. However, I do not get an error when I print only the splits with the read.nexus.splits command. Is there any reason why I get this error? Is there a problem with the file itself? Sorry about this - I am very new to programming!

**Comment by ywx1** [comment]
I use SplitsTree4, version 4.15.1. I'm downloading a trial nexus file to see if I get similar problems with other files.

**Comment by ywx1** [comment]
[Ecolitree - Copy.txt](https://github.com/KlausVigo/phangorn/files/3622182/Ecolitree.-.Copy.txt)

Can you access this file?

**Comment by ywx1** [comment]
Hi @KlausVigo !
Does this file work for you?
[Ecolitree - Copy.txt](https://github.com/KlausVigo/phangorn/files/3622216/Ecolitree.-.Copy.txt)
Thank you!

**Comment by KlausVigo** [comment]
Dear @dosshra, 
can you send me an example file. Unfortunately Splitstree 6 seems not documented well so far, not sure what they changed.
Kind regards, 
Klaus

**Comment by dosshra** [comment]
Thank you for your email
Please see file attached
Hanan Sela PhD

Institute of Evolution,

University of Haifa

Multi-Purpose Building, room 214

199 Abba-Hushi Avenue

Haifa 3498838

Israel
***@***.***
Mobile: +972-50-5727458
Office +972-48240736
Internal 52736

**Comment by dosshra** [comment]
Please see tree attached
[4splitree.stree6.gz](https://github.com/KlausVigo/phangorn/files/10455299/4splitree.stree6.gz)
Thank you
Hanan

**Comment by KlausVigo** [comment]
Dear @dosshra,
I made some bug fixes ba481aeb421693e2912dc2091d329ee4f9a15ae3 and 2e11abd86e3e4ff55c77e1acec5c2dbc26829b63. You need to install the development version, but I will send soon an new version to CRAN. SplitsTree6 does not return a networks object any more. However you can generate this in R: 
```
spl <- read.nexus.splits("4splitree.stree6")
net <- as.networx(spl)
plot(net)
``` 
Regards, 
Klaus

**Comment by dosshra** [comment]
Thank you for the  bug fixes
I works good now.

**Comment by KlausVigo** [comment]
Dear @dosshra, 
it seems Splitstree6 gets a lot of updates now. Keep me up to date if something stops working again.
