### ISSUE TITLE
densiTree does not show title

### ISSUE THREAD

**Issue by richelbilderbeek** [KlausVigo/phangorn#90]
Hi Klaus,

When I create an ordinary plot, using `plot`, adding a title is easy:

```r
plot(1:10, main = "my_title")
```

![title_around](https://user-images.githubusercontent.com/2098230/67143556-d5de0d80-f26c-11e9-9c32-f05a1e8e7ae7.png)

To add a title to a `phangorn::densiTree` function, I read in the doc:

```
...	further arguments to be passed to plot.
```

I deduce I should use `main` as an argument to get a title, as this is the same as in `plot`.

When I do that:

```r
phangorn::densiTree(c(ape::rcoal(n = 10)), main = "my_title")
```

I get a `densiTree` without a title:

![title_missing](https://user-images.githubusercontent.com/2098230/67143557-d676a400-f26c-11e9-903c-f6c16f2fdb58.png)

I wonder if either

 * I did something wrong
 * this may be a bug in `phangorn`

Full script is below, looking forward to your response :+1:

## Full script

```r
png("~/title_around.png")
plot(1:10, main = "my_title")
dev.off()

png("~/title_missing.png")
phangorn::densiTree(c(ape::rcoal(n = 10)), main = "my_title")
dev.off()
```

**Comment by KlausVigo** [comment]
@richelbilderbeek, 
Thanks for spotting this.  Should work now. 
Klaus
