### ISSUE TITLE
read.phydat error in snphylo 

### ISSUE THREAD

**Issue by birsandhu** [KlausVigo/phangorn#91]
Hi Klaus, I am getting error in reading a phylip.txt file generated by snphylo program.   
> phylip <- read.phyDat("snphylo.output.phylip.txt", format="phylip", type="DNA")
Error in obj[i, ] <- sequ : 
  number of items to replace is not a multiple of replacement length

**Comment by KlausVigo** [comment]
Dear @birsandhu, 
can you send me the data or a link to the data (or a subset of them) so that I can reproduce your problem. 
Thanks 
Klaus

**Comment by birsandhu** [comment]
[snphylo.output.phylip.txt](https://github.com/KlausVigo/phangorn/files/3979384/snphylo.output.phylip.txt)

**Comment by birsandhu** [comment]
Please see attached file that I had mentioned in my first comment. Thanks!

**Comment by birsandhu** [comment]
I had no difficulty for using this file in phylip dnaml, but it does not work in determine_bs_tree.R script (part of snphylo scripts) and gives the error I mentioned. Latter, I traced the error to read.phydat function. I also downloaded example phylip.txt files from internet and got the same error.

**Comment by KlausVigo** [comment]
Hi @birsandhu,  
there are unfortunately two different phylip formats ("interleaved" and "sequential") and the default is wrong this time. Try 
`phylip <- read.phyDat("snphylo.output.phylip.txt", format = "interleaved")`
Regards,
Klaus

**Comment by birsandhu** [comment]
> Hi @birsandhu,
> there are unfortunately two different phylip formats ("interleaved" and "sequential") and the default is wrong this time. Try
> `phylip <- read.phyDat("snphylo.output.phylip.txt", format = "interleaved")`
> Regards,
> Klaus

Much appreciated! Thanks!
