### ISSUE TITLE
creating phyolgenetic tree using continuous data

### ISSUE THREAD

**Issue by yesdavid** [KlausVigo/phangorn#94]
Dear Klaus, dear all,

is it possible to create trees and use your `phangorn`-package using continuous data? 

I work with outline data acquired from geometric morphometrics and currently use the `Rphylip::Rcontml` function, which is capable of using continuous data but only creates maximum likelihood trees.

Thanks in advance and

best regards,
David

**Comment by KlausVigo** [comment]
Hi David, 
sorry, so far I haven't implemented any methods for continuous data. What methods do you need? 
Klaus
