### ISSUE TITLE
optim.pml error missing value where TRUE/FALSE neede

### ISSUE THREAD

**Issue by Alonso-Garcia** [KlausVigo/phangorn#95]
Hello, 
I'm using phangorn (v. 2.5.5) in R studio (64-bit, R-3.6.3) to analysis my 16S data. I follow the workflow for microbiome by [Callahan et al. (2017)](https://bioconductor.org/help/course-materials/2017/BioC2017/Day1/Workshops/Microbiome/MicrobiomeWorkflowII.html).

I have some problems to construct the phylogenetic tree with _optim.pml_. Here you have the code:
`fitGTR <- update(fit, k=4, inv=0.2)`
`fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
                    rearrangement = "stochastic", 
                    control = pml.control(trace = 0))`

and this is the error: 
`Error in if (((ll1 - ll)/ll < control$eps) && rounds > 2) opti <- FALSE : 
missing value where TRUE/FALSE needed`

Could you suggest me something to solve it? 
Thank you

**Comment by KlausVigo** [comment]
Hello @Alonso-Garcia , 
that seems a bug. Is it possible to send me the alignment, e.g. using 
`saveRDS(phangAlign, file="phangAlign.rds")` , so that I can reproduce the error and
hopefully fix it.
Regards, 
Klaus

**Comment by Alonso-Garcia** [comment]
Hello @KlausVigo ,
Thank you for your quick response. 
Please, find attache the file (compressed into zip). 
Regards :) 
[phang.aling.zip](https://github.com/KlausVigo/phangorn/files/4428683/phang.aling.zip)

**Comment by Alonso-Garcia** [comment]
Thank you very much. 
It works!

**Comment by wanjauk** [comment]
Hello,
The phangorn package on CRAN seems to be on version 2.5.5 and has the bug described here. You may need to bump up its version with the current version on GitHub.
Thanks.
