### ISSUE TITLE
How to output all the bootstrap trees 

### ISSUE THREAD

**Issue by dzaccook** [KlausVigo/phangorn#96]
Hi,
Can phangorn output all the bootstrap tree files?
Thank you!

**Comment by KlausVigo** [comment]
Hi @dzaccook 
if you did something like 
`bs <- bootstrap.pml(fit, bs = 100, optNni=TRUE, multicore=TRUE)`
just use `write.tree` from ape, e.g. 
`write.tree(bs, file = 'bootstrap_trees.nwk')` 
Regards, 
Klaus
