### ISSUE TITLE
Inconsistent output from `SPR.dist()`

### ISSUE THREAD

**Issue by ms609** [KlausVigo/phangorn#97]
`SPR.dist()` gives different scores for the same tree comparison depending on whether the tree is sent separately, or as part of a list. 

Here are some example trees:

```
tr1 <- structure(list(edge = structure(c(11L, 11L, 10L, 10L, 9L, 9L, 8L, 8L, 7L,
                                         7L, 2L, 6L, 5L, 11L, 4L, 10L, 3L, 9L, 
                                         1L, 8L), .Dim = c(10L, 2L)),
                      tip.label = c("t1", "t2", "t3", "t4", "t5", "t6"), 
                      Nnode = 5),
                 class = "phylo")

tr2 <- structure(list(edge = structure(c(10L, 10L, 11L, 11L, 9L, 9L, 8L, 8L, 7L,
                                         7L, 2L, 6L, 3L, 4L, 5L, 10L, 11L, 9L, 
                                         1L, 8L), .Dim = c(10L, 2L)),
                      tip.label = c("t1", "t2", "t3", "t4", "t5", "t6"),
                      Nnode = 5),
                 class = "phylo")

tr3 <- structure(list(edge = structure(c(9L, 9L, 11L, 11L, 10L, 10L, 8L, 8L, 7L, 
                                         7L, 1L, 2L, 4L, 5L, 6L, 11L, 3L, 9L, 
                                         8L, 10L), .Dim = c(10L, 2L)),
                      Nnode = 5L, 
                      tip.label = c("t1", "t2", "t3", "t4", "t5", "t6")),
                 class = "phylo")
trs12 <- structure(list(tr1, tr2), class='multiPhylo')
```

I expect these two values to be equal:
```
SPR.dist(tr1, tr3) # Gives '1'
SPR.dist(trs12, tr3)[1] # Gives '2'
```

**Comment by KlausVigo** [comment]
Hi Martin @ms609 and Leo @leomrtns,

sorry for the late reply. Martin you spotted a bug. I added Leo as he knows the code better. 
It seems however it is not related to the `list`, but just depends on the order of the trees
```
> SPR.dist(tr1, tr3)
spr 
  1 
> SPR.dist(tr3, tr1)
spr 
  2 
```
This is hidden a bit as I have a method for comparing a tree with multiple trees, and this may flip the order internally, but bot return a vector of distances. 
Maybe we all can also start writing a paper together on different tree distance methods for R, as there is a decent number of methods in TreeDist and phangorn available. 

Regards, 
Klaus

**Comment by ms609** [comment]
Taking the minimum sounds sensible (though a shame if it's necessary to double the calculation time!)
I wonder whether it's possible to guarantee that the heuristically-derived distances satisfy the triangle inequality?
 
Klaus – if you think there's scope for a paper on tree distances in R, I'd be happy to explore how I might contribute.  The tree distance paper that motivated the 'TreeDist' package is now in the later stages of revision; if you'd like to take a look, I can e-mail a copy of the draft paper.

**Comment by ms609** [comment]
As a further thought, it's a little trickier to apply @leomrtns' `min()` approach with a single list of trees.
I suppose the approach would have to be
```r
trs123 <- structure(list(tr1, tr2, tr3), class = 'multiPhylo')
pmin(SPR.dist(trs123), SPR.dist(rev(trs123))
```
